### ISSUE TITLE
Non-descriptive error message when there is a conflict between native and non native booleans

### ISSUE THREAD

**Issue by weaversam8** [dynamoosejs/dynamoose#182]
Steps to reproduce:

1. Create a model `m` using `let M = dynamoose.model("m", {fieldA: String, fieldB: Boolean});`

2. In the DynamoDB Console, create records under the `m` table, with fieldB being a true boolean (as in `BOOL`)

3. Calling `M.get({ ... })` will give a non-descriptive error: 
```
SyntaxError: Unexpected token o in JSON at position 1
at parse (native)
at dedynamofy (/var/task/node_modules/dynamoose/lib/Attribute.js:428:14)
at Attribute.parseDynamo (/var/task/node_modules/dynamoose/lib/Attribute.js:492:13)
at Schema.parseDynamo (/var/task/node_modules/dynamoose/lib/Schema.js:182:24)
at Response.<anonymous> (/var/task/node_modules/dynamoose/lib/Model.js:401:14)
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:364:18)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
```

As a result of the `json` parameter in the `dedynamofy` being an object, but the `type` parameter being `"S"` when the `useNativeBooleans` option is not set to true on the schema. In my opinion, this error should be caught and explained.

**Comment by brandongoode** [comment]
I agree -- PR anyone?

**Comment by fishcharlie** [comment]
Similar to #281, maybe?

**Comment by fishcharlie** [comment]
Not sure this is as big of an issue anymore since we are defaulting to true for useNativeBooleans. If it is, feel free to make the argument here, and we can reopen this.

Otherwise going to close for now, due to that, and the amount of inactivity this issue has seen.
